# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tmarangoni/documents/RoCoS_2/src/ui/CodeGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CodeGenerator(object):
    def setupUi(self, Dialog_CodeGenerator):
        Dialog_CodeGenerator.setObjectName("Dialog_CodeGenerator")
        Dialog_CodeGenerator.resize(1289, 630)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        Dialog_CodeGenerator.setFont(font)
        self.gridLayout_37 = QtWidgets.QGridLayout(Dialog_CodeGenerator)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog_CodeGenerator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_37.addWidget(self.graphicsView, 2, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_afkanalyse = QtWidgets.QPushButton(Dialog_CodeGenerator)
        self.pushButton_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_afkanalyse.setObjectName("pushButton_afkanalyse")
        self.horizontalLayout_10.addWidget(self.pushButton_afkanalyse)
        self.pushButton_kkfanalyse = QtWidgets.QPushButton(Dialog_CodeGenerator)
        self.pushButton_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kkfanalyse.setObjectName("pushButton_kkfanalyse")
        self.horizontalLayout_10.addWidget(self.pushButton_kkfanalyse)
        self.pushButton_deleteall = QtWidgets.QPushButton(Dialog_CodeGenerator)
        self.pushButton_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_deleteall.setObjectName("pushButton_deleteall")
        self.horizontalLayout_10.addWidget(self.pushButton_deleteall)
        self.comboBox = QtWidgets.QComboBox(Dialog_CodeGenerator)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.pushButton_clone = QtWidgets.QPushButton(Dialog_CodeGenerator)
        self.pushButton_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_clone.setObjectName("pushButton_clone")
        self.horizontalLayout_10.addWidget(self.pushButton_clone)
        self.gridLayout_37.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.pushButton_generatesequence = QtWidgets.QPushButton(Dialog_CodeGenerator)
        self.pushButton_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_generatesequence.setObjectName("pushButton_generatesequence")
        self.gridLayout_37.addWidget(self.pushButton_generatesequence, 1, 0, 1, 1)
        self.tabs = QtWidgets.QTabWidget(Dialog_CodeGenerator)
        self.tabs.setObjectName("tabs")
        self.randomsequence = QtWidgets.QWidget()
        self.randomsequence.setObjectName("randomsequence")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.randomsequence)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.groupBox_26 = QtWidgets.QGroupBox(self.randomsequence)
        self.groupBox_26.setObjectName("groupBox_26")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.groupBox_26)
        self.gridLayout_41.setObjectName("gridLayout_41")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_41.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox_30 = QtWidgets.QGroupBox(self.groupBox_26)
        self.groupBox_30.setObjectName("groupBox_30")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.groupBox_30)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.label_29 = QtWidgets.QLabel(self.groupBox_30)
        self.label_29.setObjectName("label_29")
        self.gridLayout_42.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_30)
        self.label_33.setObjectName("label_33")
        self.gridLayout_42.addWidget(self.label_33, 1, 0, 1, 1)
        self.lineEdit_randomsequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_30)
        self.lineEdit_randomsequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_randomsequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_randomsequence_register1_initialload.setObjectName("lineEdit_randomsequence_register1_initialload")
        self.gridLayout_42.addWidget(self.lineEdit_randomsequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_randomsequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_30)
        self.lineEdit_randomsequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_randomsequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_randomsequence_register1_exponents.setObjectName("lineEdit_randomsequence_register1_exponents")
        self.gridLayout_42.addWidget(self.lineEdit_randomsequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_41.addWidget(self.groupBox_30, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_43.addWidget(self.groupBox_26, 0, 0, 1, 1)
        self.listWidget_randomsequence = QtWidgets.QListWidget(self.randomsequence)
        self.listWidget_randomsequence.setObjectName("listWidget_randomsequence")
        self.gridLayout_43.addWidget(self.listWidget_randomsequence, 0, 1, 1, 1)
        self.tabs.addTab(self.randomsequence, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_38.setObjectName("gridLayout_38")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem4, 1, 0, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_21)
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_22 = QtWidgets.QLabel(self.groupBox_22)
        self.label_22.setObjectName("label_22")
        self.gridLayout_40.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_22)
        self.label_28.setObjectName("label_28")
        self.gridLayout_40.addWidget(self.label_28, 1, 0, 1, 1)
        self.lineEdit_randomfamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_22)
        self.lineEdit_randomfamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_randomfamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_randomfamily_register1_initialload.setObjectName("lineEdit_randomfamily_register1_initialload")
        self.gridLayout_40.addWidget(self.lineEdit_randomfamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_randomfamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_22)
        self.lineEdit_randomfamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_randomfamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_randomfamily_register1_exponents.setObjectName("lineEdit_randomfamily_register1_exponents")
        self.gridLayout_40.addWidget(self.lineEdit_randomfamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_38.addWidget(self.groupBox_22, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_21, 0, 0, 1, 1)
        self.listWidget_randomfamily = QtWidgets.QListWidget(self.tab)
        self.listWidget_randomfamily.setObjectName("listWidget_randomfamily")
        self.gridLayout.addWidget(self.listWidget_randomfamily, 0, 1, 1, 1)
        self.tabs.addTab(self.tab, "")
        self.msequence = QtWidgets.QWidget()
        self.msequence.setObjectName("msequence")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.msequence)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.msequence)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_11)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_msequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_msequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_msequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_msequence_register1_initialload.setObjectName("lineEdit_msequence_register1_initialload")
        self.gridLayout_4.addWidget(self.lineEdit_msequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_msequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_msequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_msequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_msequence_register1_exponents.setObjectName("lineEdit_msequence_register1_exponents")
        self.gridLayout_4.addWidget(self.lineEdit_msequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.listWidget_msequence = QtWidgets.QListWidget(self.msequence)
        self.listWidget_msequence.setObjectName("listWidget_msequence")
        self.gridLayout_2.addWidget(self.listWidget_msequence, 0, 1, 1, 1)
        self.tabs.addTab(self.msequence, "")
        self.mfamily = QtWidgets.QWidget()
        self.mfamily.setObjectName("mfamily")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mfamily)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget_mfamily_1 = QtWidgets.QListWidget(self.mfamily)
        self.listWidget_mfamily_1.setObjectName("listWidget_mfamily_1")
        self.gridLayout_7.addWidget(self.listWidget_mfamily_1, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mfamily)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 0, 2, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_mfamily_sequence_length = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_mfamily_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_sequence_length.setObjectName("lineEdit_mfamily_sequence_length")
        self.gridLayout_8.addWidget(self.lineEdit_mfamily_sequence_length, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_13)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_13)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_mfamily_sequence_distance = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_mfamily_sequence_distance.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_sequence_distance.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_sequence_distance.setObjectName("lineEdit_mfamily_sequence_distance")
        self.gridLayout_8.addWidget(self.lineEdit_mfamily_sequence_distance, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_mfamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_mfamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_register1_initialload.setObjectName("lineEdit_mfamily_register1_initialload")
        self.gridLayout_6.addWidget(self.lineEdit_mfamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_mfamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_mfamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_register1_exponents.setObjectName("lineEdit_mfamily_register1_exponents")
        self.gridLayout_6.addWidget(self.lineEdit_mfamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_12, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.listWidget_mfamily_2 = QtWidgets.QListWidget(self.mfamily)
        self.listWidget_mfamily_2.setObjectName("listWidget_mfamily_2")
        self.gridLayout_7.addWidget(self.listWidget_mfamily_2, 1, 1, 1, 1)
        self.tabs.addTab(self.mfamily, "")
        self.goldsequence = QtWidgets.QWidget()
        self.goldsequence.setObjectName("goldsequence")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.goldsequence)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_goldsequence = QtWidgets.QListWidget(self.goldsequence)
        self.listWidget_goldsequence.setObjectName("listWidget_goldsequence")
        self.gridLayout_12.addWidget(self.listWidget_goldsequence, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.goldsequence)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_goldsequence_sequence_length = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_goldsequence_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_sequence_length.setObjectName("lineEdit_goldsequence_sequence_length")
        self.gridLayout_11.addWidget(self.lineEdit_goldsequence_sequence_length, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_23)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_23)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 1, 0, 1, 1)
        self.lineEdit_goldsequence_sequence_distances = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_goldsequence_sequence_distances.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_sequence_distances.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_sequence_distances.setObjectName("lineEdit_goldsequence_sequence_distances")
        self.gridLayout_11.addWidget(self.lineEdit_goldsequence_sequence_distances, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_23, 1, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_7 = QtWidgets.QLabel(self.groupBox_14)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_14)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_goldsequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_goldsequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register1_initialload.setObjectName("lineEdit_goldsequence_register1_initialload")
        self.gridLayout_10.addWidget(self.lineEdit_goldsequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_goldsequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_goldsequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register1_exponents.setObjectName("lineEdit_goldsequence_register1_exponents")
        self.gridLayout_10.addWidget(self.lineEdit_goldsequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_14, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem12, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem13, 0, 2, 1, 1)
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_25.setObjectName("groupBox_25")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_25)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_26 = QtWidgets.QLabel(self.groupBox_25)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_25)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_goldsequence_register2_exponents = QtWidgets.QLineEdit(self.groupBox_25)
        self.lineEdit_goldsequence_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register2_exponents.setObjectName("lineEdit_goldsequence_register2_exponents")
        self.gridLayout_13.addWidget(self.lineEdit_goldsequence_register2_exponents, 0, 1, 1, 1)
        self.lineEdit_goldsequence_register2_initialload = QtWidgets.QLineEdit(self.groupBox_25)
        self.lineEdit_goldsequence_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register2_initialload.setObjectName("lineEdit_goldsequence_register2_initialload")
        self.gridLayout_13.addWidget(self.lineEdit_goldsequence_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_25, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabs.addTab(self.goldsequence, "")
        self.goldfamily = QtWidgets.QWidget()
        self.goldfamily.setObjectName("goldfamily")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.goldfamily)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.listWidget_goldfamily = QtWidgets.QListWidget(self.goldfamily)
        self.listWidget_goldfamily.setObjectName("listWidget_goldfamily")
        self.gridLayout_18.addWidget(self.listWidget_goldfamily, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.goldfamily)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem14, 1, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem15, 0, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_15)
        self.label_9.setObjectName("label_9")
        self.gridLayout_16.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_15)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_goldfamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_goldfamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register1_initialload.setObjectName("lineEdit_goldfamily_register1_initialload")
        self.gridLayout_16.addWidget(self.lineEdit_goldfamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_goldfamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_goldfamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register1_exponents.setObjectName("lineEdit_goldfamily_register1_exponents")
        self.gridLayout_16.addWidget(self.lineEdit_goldfamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_27.setObjectName("groupBox_27")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_27)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lineEdit_goldfamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_27)
        self.lineEdit_goldfamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register2_exponents.setObjectName("lineEdit_goldfamily_register2_exponents")
        self.gridLayout_17.addWidget(self.lineEdit_goldfamily_register2_exponents, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_27)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_27, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabs.addTab(self.goldfamily, "")
        self.ogfsequence = QtWidgets.QWidget()
        self.ogfsequence.setObjectName("ogfsequence")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.ogfsequence)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_5 = QtWidgets.QGroupBox(self.ogfsequence)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 0, 2, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_16)
        self.label_11.setObjectName("label_11")
        self.gridLayout_19.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_16)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_ogfsequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ogfsequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register1_initialload.setObjectName("lineEdit_ogfsequence_register1_initialload")
        self.gridLayout_19.addWidget(self.lineEdit_ogfsequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_ogfsequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ogfsequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register1_exponents.setObjectName("lineEdit_ogfsequence_register1_exponents")
        self.gridLayout_19.addWidget(self.lineEdit_ogfsequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lineEdit_ogfsequence_register2_exponents = QtWidgets.QLineEdit(self.groupBox_28)
        self.lineEdit_ogfsequence_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register2_exponents.setObjectName("lineEdit_ogfsequence_register2_exponents")
        self.gridLayout_20.addWidget(self.lineEdit_ogfsequence_register2_exponents, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_28)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_28)
        self.label_13.setObjectName("label_13")
        self.gridLayout_20.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_ogfsequence_register2_initialload = QtWidgets.QLineEdit(self.groupBox_28)
        self.lineEdit_ogfsequence_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register2_initialload.setObjectName("lineEdit_ogfsequence_register2_initialload")
        self.gridLayout_20.addWidget(self.lineEdit_ogfsequence_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_28, 0, 1, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.listWidget_ogfsequence = QtWidgets.QListWidget(self.ogfsequence)
        self.listWidget_ogfsequence.setObjectName("listWidget_ogfsequence")
        self.gridLayout_21.addWidget(self.listWidget_ogfsequence, 0, 1, 1, 1)
        self.tabs.addTab(self.ogfsequence, "")
        self.ogffamily = QtWidgets.QWidget()
        self.ogffamily.setObjectName("ogffamily")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.ogffamily)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_6 = QtWidgets.QGroupBox(self.ogffamily)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem18, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem19, 0, 2, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_14 = QtWidgets.QLabel(self.groupBox_17)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_17)
        self.label_15.setObjectName("label_15")
        self.gridLayout_23.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_ogffamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_ogffamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register1_initialload.setObjectName("lineEdit_ogffamily_register1_initialload")
        self.gridLayout_23.addWidget(self.lineEdit_ogffamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_ogffamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_ogffamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register1_exponents.setObjectName("lineEdit_ogffamily_register1_exponents")
        self.gridLayout_23.addWidget(self.lineEdit_ogffamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_17, 0, 0, 1, 1)
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_29.setObjectName("groupBox_29")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_29)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_32 = QtWidgets.QLabel(self.groupBox_29)
        self.label_32.setObjectName("label_32")
        self.gridLayout_24.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_ogffamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_ogffamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register2_exponents.setObjectName("lineEdit_ogffamily_register2_exponents")
        self.gridLayout_24.addWidget(self.lineEdit_ogffamily_register2_exponents, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_29, 0, 1, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.listWidget_ogffamily = QtWidgets.QListWidget(self.ogffamily)
        self.listWidget_ogffamily.setObjectName("listWidget_ogffamily")
        self.gridLayout_25.addWidget(self.listWidget_ogffamily, 0, 1, 1, 1)
        self.tabs.addTab(self.ogffamily, "")
        self.kasamisequence = QtWidgets.QWidget()
        self.kasamisequence.setObjectName("kasamisequence")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.kasamisequence)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBox_7 = QtWidgets.QGroupBox(self.kasamisequence)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_16 = QtWidgets.QLabel(self.groupBox_18)
        self.label_16.setObjectName("label_16")
        self.gridLayout_27.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_18)
        self.label_17.setObjectName("label_17")
        self.gridLayout_27.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_kasamisequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_kasamisequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamisequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamisequence_register1_initialload.setObjectName("lineEdit_kasamisequence_register1_initialload")
        self.gridLayout_27.addWidget(self.lineEdit_kasamisequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_kasamisequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_kasamisequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamisequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamisequence_register1_exponents.setObjectName("lineEdit_kasamisequence_register1_exponents")
        self.gridLayout_27.addWidget(self.lineEdit_kasamisequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_18, 0, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem20, 0, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem21, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem22, 0, 1, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.listWidget_kasamisequence = QtWidgets.QListWidget(self.kasamisequence)
        self.listWidget_kasamisequence.setObjectName("listWidget_kasamisequence")
        self.gridLayout_29.addWidget(self.listWidget_kasamisequence, 0, 1, 1, 1)
        self.tabs.addTab(self.kasamisequence, "")
        self.kasamifamily = QtWidgets.QWidget()
        self.kasamifamily.setObjectName("kasamifamily")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.kasamifamily)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.groupBox_8 = QtWidgets.QGroupBox(self.kasamifamily)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_18 = QtWidgets.QLabel(self.groupBox_19)
        self.label_18.setObjectName("label_18")
        self.gridLayout_30.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_19)
        self.label_19.setObjectName("label_19")
        self.gridLayout_30.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_kasamifamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_kasamifamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register1_initialload.setObjectName("lineEdit_kasamifamily_register1_initialload")
        self.gridLayout_30.addWidget(self.lineEdit_kasamifamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_kasamifamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_kasamifamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register1_exponents.setObjectName("lineEdit_kasamifamily_register1_exponents")
        self.gridLayout_30.addWidget(self.lineEdit_kasamifamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.groupBox_19, 0, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_20 = QtWidgets.QLabel(self.groupBox_20)
        self.label_20.setObjectName("label_20")
        self.gridLayout_35.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_20)
        self.label_21.setObjectName("label_21")
        self.gridLayout_35.addWidget(self.label_21, 1, 0, 1, 1)
        self.lineEdit_kasamifamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_kasamifamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register2_exponents.setObjectName("lineEdit_kasamifamily_register2_exponents")
        self.gridLayout_35.addWidget(self.lineEdit_kasamifamily_register2_exponents, 0, 1, 1, 1)
        self.lineEdit_kasamifamily_register2_initialload = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_kasamifamily_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register2_initialload.setObjectName("lineEdit_kasamifamily_register2_initialload")
        self.gridLayout_35.addWidget(self.lineEdit_kasamifamily_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_28.addWidget(self.groupBox_20, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem23, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem24, 0, 2, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.listWidget_kasamifamily = QtWidgets.QListWidget(self.kasamifamily)
        self.listWidget_kasamifamily.setObjectName("listWidget_kasamifamily")
        self.gridLayout_31.addWidget(self.listWidget_kasamifamily, 0, 1, 1, 1)
        self.tabs.addTab(self.kasamifamily, "")
        self.ovsfsequence = QtWidgets.QWidget()
        self.ovsfsequence.setObjectName("ovsfsequence")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.ovsfsequence)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.listWidget_ovsfsequence = QtWidgets.QListWidget(self.ovsfsequence)
        self.listWidget_ovsfsequence.setObjectName("listWidget_ovsfsequence")
        self.gridLayout_36.addWidget(self.listWidget_ovsfsequence, 0, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.ovsfsequence)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_32.setObjectName("gridLayout_32")
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem25, 2, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem26, 1, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem27, 0, 0, 1, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_24.setObjectName("groupBox_24")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_24)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_25 = QtWidgets.QLabel(self.groupBox_24)
        self.label_25.setObjectName("label_25")
        self.gridLayout_33.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_ovsfsequence_sequence_length = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_ovsfsequence_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ovsfsequence_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ovsfsequence_sequence_length.setObjectName("lineEdit_ovsfsequence_sequence_length")
        self.gridLayout_33.addWidget(self.lineEdit_ovsfsequence_sequence_length, 0, 1, 1, 1)
        self.gridLayout_32.addWidget(self.groupBox_24, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem28, 1, 1, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.tabs.addTab(self.ovsfsequence, "")
        self.golaysequence = QtWidgets.QWidget()
        self.golaysequence.setObjectName("golaysequence")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.golaysequence)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.groupBox_10 = QtWidgets.QGroupBox(self.golaysequence)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_34.setObjectName("gridLayout_34")
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem29, 1, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem30, 0, 1, 1, 1)
        self.gridLayout_39.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.listWidget_golaysequence = QtWidgets.QListWidget(self.golaysequence)
        self.listWidget_golaysequence.setObjectName("listWidget_golaysequence")
        self.gridLayout_39.addWidget(self.listWidget_golaysequence, 0, 1, 1, 1)
        self.tabs.addTab(self.golaysequence, "")
        self.gridLayout_37.addWidget(self.tabs, 0, 0, 1, 2)

        self.retranslateUi(Dialog_CodeGenerator)
        self.tabs.setCurrentIndex(0)
        self.pushButton_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonGenerateSequence)
        self.pushButton_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonAFKAnalyse)
        self.pushButton_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonKKFAnalyse)
        self.pushButton_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonDeleteAll)
        self.comboBox.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxGolaySequence)
        self.pushButton_clone.pressed.connect(Dialog_CodeGenerator.pushButtonClone)
        self.lineEdit_goldsequence_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister2InitialLoad)
        self.lineEdit_kasamifamily_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister2InitialLoad)
        self.lineEdit_ogfsequence_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.pushButtonMFamilyClone)
        self.lineEdit_kasamifamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_ogfsequence_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister2Exponents)
        self.listWidget_msequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMSequence)
        self.lineEdit_mfamily_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesSequenceLength)
        self.lineEdit_ogffamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister1Exponents)
        self.lineEdit_goldfamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister2Exponents)
        self.lineEdit_kasamifamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister1Exponents)
        self.lineEdit_ogffamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister2Exponents)
        self.lineEdit_goldsequence_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesSequenceLength)
        self.listWidget_mfamily_1.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMFamily1)
        self.listWidget_kasamifamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetKasamiFamily)
        self.lineEdit_kasamisequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiSequencePropertiesRegister1Exponents)
        self.lineEdit_ogffamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister1InitialLoad)
        self.listWidget_goldfamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGoldFamily)
        self.lineEdit_kasamifamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister2Exponents)
        self.lineEdit_goldsequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister1Exponents)
        self.lineEdit_ogfsequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister1Exponents)
        self.listWidget_ogfsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOGFSequence)
        self.lineEdit_msequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditMSequencePropertiesRegister1Exponents)
        self.listWidget_golaysequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGolaySequence)
        self.listWidget_ovsfsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOVSFSequence)
        self.listWidget_goldfamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOGFFamily)
        self.lineEdit_goldfamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister1Exponents)
        self.listWidget_goldsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGoldSequence)
        self.lineEdit_mfamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_ovsfsequence_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditOVSFSequenceSequenceLength)
        self.lineEdit_kasamisequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiSequencePropertiesRegister1InitialLoad)
        self.listWidget_kasamisequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetKasamiSequence)
        self.lineEdit_goldsequence_sequence_distances.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesSequenceDistance)
        self.lineEdit_goldsequence_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister2Exponents)
        self.lineEdit_goldsequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister1InitialLoad)
        self.lineEdit_mfamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesRegister1Exponents)
        self.lineEdit_msequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditMSequencePropertiesRegister1InitialLoad)
        self.lineEdit_goldfamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister1InitialLoad)
        self.listWidget_mfamily_2.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMFamily2)
        self.tabs.currentChanged['int'].connect(Dialog_CodeGenerator.tabs)
        self.lineEdit_mfamily_sequence_distance.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesSequenceDistance)
        self.lineEdit_ogfsequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister1InitialLoad)
        QtCore.QMetaObject.connectSlotsByName(Dialog_CodeGenerator)

    def retranslateUi(self, Dialog_CodeGenerator):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CodeGenerator.setWindowTitle(_translate("Dialog_CodeGenerator", "RoCoS 2 - Code Generator"))
        self.pushButton_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.pushButton_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.groupBox_26.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_30.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_29.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_33.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.randomsequence), _translate("Dialog_CodeGenerator", "Random-Sequence"))
        self.groupBox_21.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_22.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_22.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_28.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("Dialog_CodeGenerator", "Random-Family"))
        self.groupBox.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_11.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_2.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.msequence), _translate("Dialog_CodeGenerator", "m-Sequence"))
        self.groupBox_2.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_13.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_5.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.label_6.setText(_translate("Dialog_CodeGenerator", "Distances"))
        self.groupBox_12.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_3.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_4.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.mfamily), _translate("Dialog_CodeGenerator", "m-Family"))
        self.groupBox_3.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_23.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_23.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.label_24.setText(_translate("Dialog_CodeGenerator", "Distances"))
        self.groupBox_14.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_7.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_8.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_25.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_26.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_27.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.goldsequence), _translate("Dialog_CodeGenerator", "Gold-Sequence"))
        self.groupBox_4.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_15.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_9.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_10.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_27.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_30.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.tabs.setTabText(self.tabs.indexOf(self.goldfamily), _translate("Dialog_CodeGenerator", "Gold-Family"))
        self.groupBox_5.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_16.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_11.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_12.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_28.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_31.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_13.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.ogfsequence), _translate("Dialog_CodeGenerator", "OGF-Sequence"))
        self.groupBox_6.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_17.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_14.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_15.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_29.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_32.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.tabs.setTabText(self.tabs.indexOf(self.ogffamily), _translate("Dialog_CodeGenerator", "OGF-Family"))
        self.groupBox_7.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_18.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_16.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_17.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.kasamisequence), _translate("Dialog_CodeGenerator", "Kasami-Sequence"))
        self.groupBox_8.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_19.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_18.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_19.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_20.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_20.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_21.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.kasamifamily), _translate("Dialog_CodeGenerator", "Kasami-Family"))
        self.groupBox_9.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_24.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_25.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.tabs.setTabText(self.tabs.indexOf(self.ovsfsequence), _translate("Dialog_CodeGenerator", "OVSF-Sequence"))
        self.groupBox_10.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.tabs.setTabText(self.tabs.indexOf(self.golaysequence), _translate("Dialog_CodeGenerator", "Golay-Sequence"))
