# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tmarangoni/documents/RoCoS_2/src/ui/CodeGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CodeGenerator(object):
    def setupUi(self, Dialog_CodeGenerator):
        Dialog_CodeGenerator.setObjectName("Dialog_CodeGenerator")
        Dialog_CodeGenerator.resize(1250, 630)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        Dialog_CodeGenerator.setFont(font)
        self.gridLayout_37 = QtWidgets.QGridLayout(Dialog_CodeGenerator)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.tabs = QtWidgets.QTabWidget(Dialog_CodeGenerator)
        self.tabs.setObjectName("tabs")
        self.msequence = QtWidgets.QWidget()
        self.msequence.setObjectName("msequence")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.msequence)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_msequence_afkanalyse = QtWidgets.QPushButton(self.msequence)
        self.pushButton_msequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_msequence_afkanalyse.setObjectName("pushButton_msequence_afkanalyse")
        self.horizontalLayout.addWidget(self.pushButton_msequence_afkanalyse)
        self.pushButton_msequence_kkfanalyse = QtWidgets.QPushButton(self.msequence)
        self.pushButton_msequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_msequence_kkfanalyse.setObjectName("pushButton_msequence_kkfanalyse")
        self.horizontalLayout.addWidget(self.pushButton_msequence_kkfanalyse)
        self.pushButton_msequence_deletall = QtWidgets.QPushButton(self.msequence)
        self.pushButton_msequence_deletall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_msequence_deletall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_msequence_deletall.setObjectName("pushButton_msequence_deletall")
        self.horizontalLayout.addWidget(self.pushButton_msequence_deletall)
        self.comboBox_msequence = QtWidgets.QComboBox(self.msequence)
        self.comboBox_msequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_msequence.setObjectName("comboBox_msequence")
        self.comboBox_msequence.addItem("")
        self.comboBox_msequence.addItem("")
        self.comboBox_msequence.addItem("")
        self.comboBox_msequence.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_msequence)
        self.pushButton_msequence_clone = QtWidgets.QPushButton(self.msequence)
        self.pushButton_msequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_msequence_clone.setObjectName("pushButton_msequence_clone")
        self.horizontalLayout.addWidget(self.pushButton_msequence_clone)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.msequence)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_11)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_11)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_msequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_msequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_msequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_msequence_register1_initialload.setObjectName("lineEdit_msequence_register1_initialload")
        self.gridLayout_4.addWidget(self.lineEdit_msequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_msequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_msequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_msequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_msequence_register1_exponents.setObjectName("lineEdit_msequence_register1_exponents")
        self.gridLayout_4.addWidget(self.lineEdit_msequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphicsView_msequence = QtWidgets.QGraphicsView(self.msequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_msequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_msequence.setSizePolicy(sizePolicy)
        self.graphicsView_msequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_msequence.setObjectName("graphicsView_msequence")
        self.gridLayout_2.addWidget(self.graphicsView_msequence, 2, 0, 1, 2)
        self.pushButton_msequence_generatesequence = QtWidgets.QPushButton(self.msequence)
        self.pushButton_msequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_msequence_generatesequence.setObjectName("pushButton_msequence_generatesequence")
        self.gridLayout_2.addWidget(self.pushButton_msequence_generatesequence, 1, 0, 1, 1)
        self.listWidget_msequence = QtWidgets.QListWidget(self.msequence)
        self.listWidget_msequence.setObjectName("listWidget_msequence")
        self.gridLayout_2.addWidget(self.listWidget_msequence, 0, 1, 1, 1)
        self.tabs.addTab(self.msequence, "")
        self.mfamily = QtWidgets.QWidget()
        self.mfamily.setObjectName("mfamily")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mfamily)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_mfamily_afkanalyse = QtWidgets.QPushButton(self.mfamily)
        self.pushButton_mfamily_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_mfamily_afkanalyse.setObjectName("pushButton_mfamily_afkanalyse")
        self.horizontalLayout_2.addWidget(self.pushButton_mfamily_afkanalyse)
        self.pushButton_mfamily_kkfanalyse = QtWidgets.QPushButton(self.mfamily)
        self.pushButton_mfamily_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_mfamily_kkfanalyse.setObjectName("pushButton_mfamily_kkfanalyse")
        self.horizontalLayout_2.addWidget(self.pushButton_mfamily_kkfanalyse)
        self.pushButton_mfamily_deleteall = QtWidgets.QPushButton(self.mfamily)
        self.pushButton_mfamily_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_mfamily_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_mfamily_deleteall.setObjectName("pushButton_mfamily_deleteall")
        self.horizontalLayout_2.addWidget(self.pushButton_mfamily_deleteall)
        self.comboBox_mfamily = QtWidgets.QComboBox(self.mfamily)
        self.comboBox_mfamily.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_mfamily.setObjectName("comboBox_mfamily")
        self.comboBox_mfamily.addItem("")
        self.comboBox_mfamily.addItem("")
        self.comboBox_mfamily.addItem("")
        self.comboBox_mfamily.addItem("")
        self.comboBox_mfamily.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_mfamily)
        self.pushButton_mfamily_clone = QtWidgets.QPushButton(self.mfamily)
        self.pushButton_mfamily_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_mfamily_clone.setObjectName("pushButton_mfamily_clone")
        self.horizontalLayout_2.addWidget(self.pushButton_mfamily_clone)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.pushButton_mfamily_generatesequence = QtWidgets.QPushButton(self.mfamily)
        self.pushButton_mfamily_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_mfamily_generatesequence.setObjectName("pushButton_mfamily_generatesequence")
        self.gridLayout_7.addWidget(self.pushButton_mfamily_generatesequence, 2, 0, 1, 1)
        self.graphicsView_mfamily = QtWidgets.QGraphicsView(self.mfamily)
        self.graphicsView_mfamily.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_mfamily.setObjectName("graphicsView_mfamily")
        self.gridLayout_7.addWidget(self.graphicsView_mfamily, 3, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mfamily)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 2, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_mfamily_sequence_length = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_mfamily_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_sequence_length.setObjectName("lineEdit_mfamily_sequence_length")
        self.gridLayout_8.addWidget(self.lineEdit_mfamily_sequence_length, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_13)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_13)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_mfamily_sequence_distance = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_mfamily_sequence_distance.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_sequence_distance.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_sequence_distance.setObjectName("lineEdit_mfamily_sequence_distance")
        self.gridLayout_8.addWidget(self.lineEdit_mfamily_sequence_distance, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_mfamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_mfamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_register1_initialload.setObjectName("lineEdit_mfamily_register1_initialload")
        self.gridLayout_6.addWidget(self.lineEdit_mfamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_mfamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_mfamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_mfamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_mfamily_register1_exponents.setObjectName("lineEdit_mfamily_register1_exponents")
        self.gridLayout_6.addWidget(self.lineEdit_mfamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_12, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.listWidget_mfamily_1 = QtWidgets.QListWidget(self.mfamily)
        self.listWidget_mfamily_1.setObjectName("listWidget_mfamily_1")
        self.gridLayout_7.addWidget(self.listWidget_mfamily_1, 0, 1, 1, 1)
        self.listWidget_mfamily_2 = QtWidgets.QListWidget(self.mfamily)
        self.listWidget_mfamily_2.setObjectName("listWidget_mfamily_2")
        self.gridLayout_7.addWidget(self.listWidget_mfamily_2, 1, 1, 1, 1)
        self.tabs.addTab(self.mfamily, "")
        self.goldsequence = QtWidgets.QWidget()
        self.goldsequence.setObjectName("goldsequence")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.goldsequence)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.goldsequence)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_goldsequence_sequence_length = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_goldsequence_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_sequence_length.setObjectName("lineEdit_goldsequence_sequence_length")
        self.gridLayout_11.addWidget(self.lineEdit_goldsequence_sequence_length, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_23)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_23)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 1, 0, 1, 1)
        self.lineEdit_goldsequence_sequence_distances = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_goldsequence_sequence_distances.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_sequence_distances.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_sequence_distances.setObjectName("lineEdit_goldsequence_sequence_distances")
        self.gridLayout_11.addWidget(self.lineEdit_goldsequence_sequence_distances, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_23, 1, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_7 = QtWidgets.QLabel(self.groupBox_14)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_14)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_goldsequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_goldsequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register1_initialload.setObjectName("lineEdit_goldsequence_register1_initialload")
        self.gridLayout_10.addWidget(self.lineEdit_goldsequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_goldsequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_goldsequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register1_exponents.setObjectName("lineEdit_goldsequence_register1_exponents")
        self.gridLayout_10.addWidget(self.lineEdit_goldsequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_14, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 2, 1, 1)
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_25.setObjectName("groupBox_25")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_25)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_26 = QtWidgets.QLabel(self.groupBox_25)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_25)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_goldsequence_register2_exponents = QtWidgets.QLineEdit(self.groupBox_25)
        self.lineEdit_goldsequence_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register2_exponents.setObjectName("lineEdit_goldsequence_register2_exponents")
        self.gridLayout_13.addWidget(self.lineEdit_goldsequence_register2_exponents, 0, 1, 1, 1)
        self.lineEdit_goldsequence_register2_initialload = QtWidgets.QLineEdit(self.groupBox_25)
        self.lineEdit_goldsequence_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldsequence_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldsequence_register2_initialload.setObjectName("lineEdit_goldsequence_register2_initialload")
        self.gridLayout_13.addWidget(self.lineEdit_goldsequence_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_25, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.pushButton_goldsequence_generatesequence = QtWidgets.QPushButton(self.goldsequence)
        self.pushButton_goldsequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldsequence_generatesequence.setObjectName("pushButton_goldsequence_generatesequence")
        self.gridLayout_12.addWidget(self.pushButton_goldsequence_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_goldsequence_afkanalyse = QtWidgets.QPushButton(self.goldsequence)
        self.pushButton_goldsequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldsequence_afkanalyse.setObjectName("pushButton_goldsequence_afkanalyse")
        self.horizontalLayout_3.addWidget(self.pushButton_goldsequence_afkanalyse)
        self.pushButton_goldsequence_kkfanalyse = QtWidgets.QPushButton(self.goldsequence)
        self.pushButton_goldsequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldsequence_kkfanalyse.setObjectName("pushButton_goldsequence_kkfanalyse")
        self.horizontalLayout_3.addWidget(self.pushButton_goldsequence_kkfanalyse)
        self.pushButton_goldsequence_deleteall = QtWidgets.QPushButton(self.goldsequence)
        self.pushButton_goldsequence_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldsequence_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)\n"
"")
        self.pushButton_goldsequence_deleteall.setObjectName("pushButton_goldsequence_deleteall")
        self.horizontalLayout_3.addWidget(self.pushButton_goldsequence_deleteall)
        self.comboBox_goldsequence = QtWidgets.QComboBox(self.goldsequence)
        self.comboBox_goldsequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_goldsequence.setObjectName("comboBox_goldsequence")
        self.comboBox_goldsequence.addItem("")
        self.comboBox_goldsequence.addItem("")
        self.comboBox_goldsequence.addItem("")
        self.comboBox_goldsequence.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_goldsequence)
        self.pushButton_goldsequence_clone = QtWidgets.QPushButton(self.goldsequence)
        self.pushButton_goldsequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldsequence_clone.setObjectName("pushButton_goldsequence_clone")
        self.horizontalLayout_3.addWidget(self.pushButton_goldsequence_clone)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.graphicsView_goldsequence = QtWidgets.QGraphicsView(self.goldsequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_goldsequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_goldsequence.setSizePolicy(sizePolicy)
        self.graphicsView_goldsequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_goldsequence.setObjectName("graphicsView_goldsequence")
        self.gridLayout_12.addWidget(self.graphicsView_goldsequence, 2, 0, 1, 2)
        self.listWidget_goldsequence = QtWidgets.QListWidget(self.goldsequence)
        self.listWidget_goldsequence.setObjectName("listWidget_goldsequence")
        self.gridLayout_12.addWidget(self.listWidget_goldsequence, 0, 1, 1, 1)
        self.tabs.addTab(self.goldsequence, "")
        self.goldfamily = QtWidgets.QWidget()
        self.goldfamily.setObjectName("goldfamily")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.goldfamily)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_4 = QtWidgets.QGroupBox(self.goldfamily)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem9, 0, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_15)
        self.label_9.setObjectName("label_9")
        self.gridLayout_16.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_15)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_goldfamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_goldfamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register1_initialload.setObjectName("lineEdit_goldfamily_register1_initialload")
        self.gridLayout_16.addWidget(self.lineEdit_goldfamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_goldfamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_goldfamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register1_exponents.setObjectName("lineEdit_goldfamily_register1_exponents")
        self.gridLayout_16.addWidget(self.lineEdit_goldfamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_27.setObjectName("groupBox_27")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_27)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.lineEdit_goldfamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_27)
        self.lineEdit_goldfamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_goldfamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_goldfamily_register2_exponents.setObjectName("lineEdit_goldfamily_register2_exponents")
        self.gridLayout_17.addWidget(self.lineEdit_goldfamily_register2_exponents, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_27)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_27, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.pushButton_goldfamily_generatesequence = QtWidgets.QPushButton(self.goldfamily)
        self.pushButton_goldfamily_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldfamily_generatesequence.setObjectName("pushButton_goldfamily_generatesequence")
        self.gridLayout_18.addWidget(self.pushButton_goldfamily_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_goldfamily_afkanalyse = QtWidgets.QPushButton(self.goldfamily)
        self.pushButton_goldfamily_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldfamily_afkanalyse.setObjectName("pushButton_goldfamily_afkanalyse")
        self.horizontalLayout_4.addWidget(self.pushButton_goldfamily_afkanalyse)
        self.pushButton_goldfamily_kkfanalyse = QtWidgets.QPushButton(self.goldfamily)
        self.pushButton_goldfamily_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldfamily_kkfanalyse.setObjectName("pushButton_goldfamily_kkfanalyse")
        self.horizontalLayout_4.addWidget(self.pushButton_goldfamily_kkfanalyse)
        self.pushButton_goldfamily_deleteall = QtWidgets.QPushButton(self.goldfamily)
        self.pushButton_goldfamily_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldfamily_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_goldfamily_deleteall.setObjectName("pushButton_goldfamily_deleteall")
        self.horizontalLayout_4.addWidget(self.pushButton_goldfamily_deleteall)
        self.comboBox_goldfamily = QtWidgets.QComboBox(self.goldfamily)
        self.comboBox_goldfamily.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_goldfamily.setObjectName("comboBox_goldfamily")
        self.comboBox_goldfamily.addItem("")
        self.comboBox_goldfamily.addItem("")
        self.comboBox_goldfamily.addItem("")
        self.comboBox_goldfamily.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_goldfamily)
        self.pushButton_goldfamily_clone = QtWidgets.QPushButton(self.goldfamily)
        self.pushButton_goldfamily_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_goldfamily_clone.setObjectName("pushButton_goldfamily_clone")
        self.horizontalLayout_4.addWidget(self.pushButton_goldfamily_clone)
        self.gridLayout_18.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.graphicsView_goldfamily = QtWidgets.QGraphicsView(self.goldfamily)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_goldfamily.sizePolicy().hasHeightForWidth())
        self.graphicsView_goldfamily.setSizePolicy(sizePolicy)
        self.graphicsView_goldfamily.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_goldfamily.setObjectName("graphicsView_goldfamily")
        self.gridLayout_18.addWidget(self.graphicsView_goldfamily, 2, 0, 1, 2)
        self.listWidget_goldfamily = QtWidgets.QListWidget(self.goldfamily)
        self.listWidget_goldfamily.setObjectName("listWidget_goldfamily")
        self.gridLayout_18.addWidget(self.listWidget_goldfamily, 0, 1, 1, 1)
        self.tabs.addTab(self.goldfamily, "")
        self.ogfsequence = QtWidgets.QWidget()
        self.ogfsequence.setObjectName("ogfsequence")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.ogfsequence)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_5 = QtWidgets.QGroupBox(self.ogfsequence)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem11, 0, 2, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_16)
        self.label_11.setObjectName("label_11")
        self.gridLayout_19.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_16)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_ogfsequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ogfsequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register1_initialload.setObjectName("lineEdit_ogfsequence_register1_initialload")
        self.gridLayout_19.addWidget(self.lineEdit_ogfsequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_ogfsequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ogfsequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register1_exponents.setObjectName("lineEdit_ogfsequence_register1_exponents")
        self.gridLayout_19.addWidget(self.lineEdit_ogfsequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lineEdit_ogfsequence_register2_exponents = QtWidgets.QLineEdit(self.groupBox_28)
        self.lineEdit_ogfsequence_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register2_exponents.setObjectName("lineEdit_ogfsequence_register2_exponents")
        self.gridLayout_20.addWidget(self.lineEdit_ogfsequence_register2_exponents, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_28)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_28)
        self.label_13.setObjectName("label_13")
        self.gridLayout_20.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_ogfsequence_register2_initialload = QtWidgets.QLineEdit(self.groupBox_28)
        self.lineEdit_ogfsequence_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogfsequence_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogfsequence_register2_initialload.setObjectName("lineEdit_ogfsequence_register2_initialload")
        self.gridLayout_20.addWidget(self.lineEdit_ogfsequence_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_28, 0, 1, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.pushButton_ogfsequence_generatesequence = QtWidgets.QPushButton(self.ogfsequence)
        self.pushButton_ogfsequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogfsequence_generatesequence.setObjectName("pushButton_ogfsequence_generatesequence")
        self.gridLayout_21.addWidget(self.pushButton_ogfsequence_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_ogfsequence_afkanalyse = QtWidgets.QPushButton(self.ogfsequence)
        self.pushButton_ogfsequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogfsequence_afkanalyse.setObjectName("pushButton_ogfsequence_afkanalyse")
        self.horizontalLayout_5.addWidget(self.pushButton_ogfsequence_afkanalyse)
        self.pushButton_ogfsequence_kkfanalyse = QtWidgets.QPushButton(self.ogfsequence)
        self.pushButton_ogfsequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogfsequence_kkfanalyse.setObjectName("pushButton_ogfsequence_kkfanalyse")
        self.horizontalLayout_5.addWidget(self.pushButton_ogfsequence_kkfanalyse)
        self.pushButton_ogfsequence_deleteall = QtWidgets.QPushButton(self.ogfsequence)
        self.pushButton_ogfsequence_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogfsequence_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_ogfsequence_deleteall.setObjectName("pushButton_ogfsequence_deleteall")
        self.horizontalLayout_5.addWidget(self.pushButton_ogfsequence_deleteall)
        self.comboBox_ogfsequence = QtWidgets.QComboBox(self.ogfsequence)
        self.comboBox_ogfsequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_ogfsequence.setObjectName("comboBox_ogfsequence")
        self.comboBox_ogfsequence.addItem("")
        self.comboBox_ogfsequence.addItem("")
        self.comboBox_ogfsequence.addItem("")
        self.comboBox_ogfsequence.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_ogfsequence)
        self.pushButton_ogfsequence_clone = QtWidgets.QPushButton(self.ogfsequence)
        self.pushButton_ogfsequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogfsequence_clone.setObjectName("pushButton_ogfsequence_clone")
        self.horizontalLayout_5.addWidget(self.pushButton_ogfsequence_clone)
        self.gridLayout_21.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.graphicsView_ogfsequence = QtWidgets.QGraphicsView(self.ogfsequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_ogfsequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_ogfsequence.setSizePolicy(sizePolicy)
        self.graphicsView_ogfsequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_ogfsequence.setObjectName("graphicsView_ogfsequence")
        self.gridLayout_21.addWidget(self.graphicsView_ogfsequence, 2, 0, 1, 2)
        self.listWidget_ogfsequence = QtWidgets.QListWidget(self.ogfsequence)
        self.listWidget_ogfsequence.setObjectName("listWidget_ogfsequence")
        self.gridLayout_21.addWidget(self.listWidget_ogfsequence, 0, 1, 1, 1)
        self.tabs.addTab(self.ogfsequence, "")
        self.ogffamily = QtWidgets.QWidget()
        self.ogffamily.setObjectName("ogffamily")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.ogffamily)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_6 = QtWidgets.QGroupBox(self.ogffamily)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem13, 0, 2, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_14 = QtWidgets.QLabel(self.groupBox_17)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_17)
        self.label_15.setObjectName("label_15")
        self.gridLayout_23.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_ogffamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_ogffamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register1_initialload.setObjectName("lineEdit_ogffamily_register1_initialload")
        self.gridLayout_23.addWidget(self.lineEdit_ogffamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_ogffamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_ogffamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register1_exponents.setObjectName("lineEdit_ogffamily_register1_exponents")
        self.gridLayout_23.addWidget(self.lineEdit_ogffamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_17, 0, 0, 1, 1)
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_29.setObjectName("groupBox_29")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_29)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_32 = QtWidgets.QLabel(self.groupBox_29)
        self.label_32.setObjectName("label_32")
        self.gridLayout_24.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_ogffamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_29)
        self.lineEdit_ogffamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ogffamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ogffamily_register2_exponents.setObjectName("lineEdit_ogffamily_register2_exponents")
        self.gridLayout_24.addWidget(self.lineEdit_ogffamily_register2_exponents, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_29, 0, 1, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.pushButton_ogffamily_generatesequence = QtWidgets.QPushButton(self.ogffamily)
        self.pushButton_ogffamily_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogffamily_generatesequence.setObjectName("pushButton_ogffamily_generatesequence")
        self.gridLayout_25.addWidget(self.pushButton_ogffamily_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_ogffamily_afkanalyse = QtWidgets.QPushButton(self.ogffamily)
        self.pushButton_ogffamily_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogffamily_afkanalyse.setObjectName("pushButton_ogffamily_afkanalyse")
        self.horizontalLayout_6.addWidget(self.pushButton_ogffamily_afkanalyse)
        self.pushButton_ogffamily_kkfanalyse = QtWidgets.QPushButton(self.ogffamily)
        self.pushButton_ogffamily_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogffamily_kkfanalyse.setObjectName("pushButton_ogffamily_kkfanalyse")
        self.horizontalLayout_6.addWidget(self.pushButton_ogffamily_kkfanalyse)
        self.pushButton_ogffamily_deleteall = QtWidgets.QPushButton(self.ogffamily)
        self.pushButton_ogffamily_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogffamily_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_ogffamily_deleteall.setObjectName("pushButton_ogffamily_deleteall")
        self.horizontalLayout_6.addWidget(self.pushButton_ogffamily_deleteall)
        self.comboBox_ogffamily = QtWidgets.QComboBox(self.ogffamily)
        self.comboBox_ogffamily.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_ogffamily.setObjectName("comboBox_ogffamily")
        self.comboBox_ogffamily.addItem("")
        self.comboBox_ogffamily.addItem("")
        self.comboBox_ogffamily.addItem("")
        self.comboBox_ogffamily.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_ogffamily)
        self.pushButton_ogffamily_clone = QtWidgets.QPushButton(self.ogffamily)
        self.pushButton_ogffamily_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ogffamily_clone.setObjectName("pushButton_ogffamily_clone")
        self.horizontalLayout_6.addWidget(self.pushButton_ogffamily_clone)
        self.gridLayout_25.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.graphicsView_ogffamily = QtWidgets.QGraphicsView(self.ogffamily)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_ogffamily.sizePolicy().hasHeightForWidth())
        self.graphicsView_ogffamily.setSizePolicy(sizePolicy)
        self.graphicsView_ogffamily.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_ogffamily.setObjectName("graphicsView_ogffamily")
        self.gridLayout_25.addWidget(self.graphicsView_ogffamily, 2, 0, 1, 2)
        self.listWidget_ogffamily = QtWidgets.QListWidget(self.ogffamily)
        self.listWidget_ogffamily.setObjectName("listWidget_ogffamily")
        self.gridLayout_25.addWidget(self.listWidget_ogffamily, 0, 1, 1, 1)
        self.tabs.addTab(self.ogffamily, "")
        self.kasamisequence = QtWidgets.QWidget()
        self.kasamisequence.setObjectName("kasamisequence")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.kasamisequence)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBox_7 = QtWidgets.QGroupBox(self.kasamisequence)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_16 = QtWidgets.QLabel(self.groupBox_18)
        self.label_16.setObjectName("label_16")
        self.gridLayout_27.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_18)
        self.label_17.setObjectName("label_17")
        self.gridLayout_27.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_kasamisequence_register1_initialload = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_kasamisequence_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamisequence_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamisequence_register1_initialload.setObjectName("lineEdit_kasamisequence_register1_initialload")
        self.gridLayout_27.addWidget(self.lineEdit_kasamisequence_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_kasamisequence_register1_exponents = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_kasamisequence_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamisequence_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamisequence_register1_exponents.setObjectName("lineEdit_kasamisequence_register1_exponents")
        self.gridLayout_27.addWidget(self.lineEdit_kasamisequence_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_18, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem14, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem15, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem16, 0, 1, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.pushButton_kasamisequence_generatesequence = QtWidgets.QPushButton(self.kasamisequence)
        self.pushButton_kasamisequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamisequence_generatesequence.setObjectName("pushButton_kasamisequence_generatesequence")
        self.gridLayout_29.addWidget(self.pushButton_kasamisequence_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_kasamisequence_afkanalyse = QtWidgets.QPushButton(self.kasamisequence)
        self.pushButton_kasamisequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamisequence_afkanalyse.setObjectName("pushButton_kasamisequence_afkanalyse")
        self.horizontalLayout_7.addWidget(self.pushButton_kasamisequence_afkanalyse)
        self.pushButton_kasamisequence_kkfanalyse = QtWidgets.QPushButton(self.kasamisequence)
        self.pushButton_kasamisequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamisequence_kkfanalyse.setObjectName("pushButton_kasamisequence_kkfanalyse")
        self.horizontalLayout_7.addWidget(self.pushButton_kasamisequence_kkfanalyse)
        self.pushButton_kasamisequence_deleteall = QtWidgets.QPushButton(self.kasamisequence)
        self.pushButton_kasamisequence_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamisequence_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_kasamisequence_deleteall.setObjectName("pushButton_kasamisequence_deleteall")
        self.horizontalLayout_7.addWidget(self.pushButton_kasamisequence_deleteall)
        self.comboBox_kasamisequence = QtWidgets.QComboBox(self.kasamisequence)
        self.comboBox_kasamisequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_kasamisequence.setObjectName("comboBox_kasamisequence")
        self.comboBox_kasamisequence.addItem("")
        self.comboBox_kasamisequence.addItem("")
        self.comboBox_kasamisequence.addItem("")
        self.comboBox_kasamisequence.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_kasamisequence)
        self.pushButton_kasamisequence_clone = QtWidgets.QPushButton(self.kasamisequence)
        self.pushButton_kasamisequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamisequence_clone.setObjectName("pushButton_kasamisequence_clone")
        self.horizontalLayout_7.addWidget(self.pushButton_kasamisequence_clone)
        self.gridLayout_29.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.graphicsView_kasamisequence = QtWidgets.QGraphicsView(self.kasamisequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_kasamisequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_kasamisequence.setSizePolicy(sizePolicy)
        self.graphicsView_kasamisequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_kasamisequence.setObjectName("graphicsView_kasamisequence")
        self.gridLayout_29.addWidget(self.graphicsView_kasamisequence, 2, 0, 1, 2)
        self.listWidget_kasamisequence = QtWidgets.QListWidget(self.kasamisequence)
        self.listWidget_kasamisequence.setObjectName("listWidget_kasamisequence")
        self.gridLayout_29.addWidget(self.listWidget_kasamisequence, 0, 1, 1, 1)
        self.tabs.addTab(self.kasamisequence, "")
        self.kasamifamily = QtWidgets.QWidget()
        self.kasamifamily.setObjectName("kasamifamily")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.kasamifamily)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.groupBox_8 = QtWidgets.QGroupBox(self.kasamifamily)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_18 = QtWidgets.QLabel(self.groupBox_19)
        self.label_18.setObjectName("label_18")
        self.gridLayout_30.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_19)
        self.label_19.setObjectName("label_19")
        self.gridLayout_30.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_kasamifamily_register1_initialload = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_kasamifamily_register1_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register1_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register1_initialload.setObjectName("lineEdit_kasamifamily_register1_initialload")
        self.gridLayout_30.addWidget(self.lineEdit_kasamifamily_register1_initialload, 1, 1, 1, 1)
        self.lineEdit_kasamifamily_register1_exponents = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_kasamifamily_register1_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register1_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register1_exponents.setObjectName("lineEdit_kasamifamily_register1_exponents")
        self.gridLayout_30.addWidget(self.lineEdit_kasamifamily_register1_exponents, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.groupBox_19, 0, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_20 = QtWidgets.QLabel(self.groupBox_20)
        self.label_20.setObjectName("label_20")
        self.gridLayout_35.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_20)
        self.label_21.setObjectName("label_21")
        self.gridLayout_35.addWidget(self.label_21, 1, 0, 1, 1)
        self.lineEdit_kasamifamily_register2_exponents = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_kasamifamily_register2_exponents.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register2_exponents.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register2_exponents.setObjectName("lineEdit_kasamifamily_register2_exponents")
        self.gridLayout_35.addWidget(self.lineEdit_kasamifamily_register2_exponents, 0, 1, 1, 1)
        self.lineEdit_kasamifamily_register2_initialload = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_kasamifamily_register2_initialload.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_kasamifamily_register2_initialload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_kasamifamily_register2_initialload.setObjectName("lineEdit_kasamifamily_register2_initialload")
        self.gridLayout_35.addWidget(self.lineEdit_kasamifamily_register2_initialload, 1, 1, 1, 1)
        self.gridLayout_28.addWidget(self.groupBox_20, 0, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem17, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem18, 0, 2, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.pushButton_kasamifamily_generatesequence = QtWidgets.QPushButton(self.kasamifamily)
        self.pushButton_kasamifamily_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamifamily_generatesequence.setObjectName("pushButton_kasamifamily_generatesequence")
        self.gridLayout_31.addWidget(self.pushButton_kasamifamily_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_kasamifamily_afkanalyse = QtWidgets.QPushButton(self.kasamifamily)
        self.pushButton_kasamifamily_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamifamily_afkanalyse.setObjectName("pushButton_kasamifamily_afkanalyse")
        self.horizontalLayout_8.addWidget(self.pushButton_kasamifamily_afkanalyse)
        self.pushButton_kasamifamily_kkfanalyse = QtWidgets.QPushButton(self.kasamifamily)
        self.pushButton_kasamifamily_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamifamily_kkfanalyse.setObjectName("pushButton_kasamifamily_kkfanalyse")
        self.horizontalLayout_8.addWidget(self.pushButton_kasamifamily_kkfanalyse)
        self.pushButton_kasamifamily_deleteall = QtWidgets.QPushButton(self.kasamifamily)
        self.pushButton_kasamifamily_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamifamily_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_kasamifamily_deleteall.setObjectName("pushButton_kasamifamily_deleteall")
        self.horizontalLayout_8.addWidget(self.pushButton_kasamifamily_deleteall)
        self.comboBox_kasamifamily = QtWidgets.QComboBox(self.kasamifamily)
        self.comboBox_kasamifamily.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_kasamifamily.setObjectName("comboBox_kasamifamily")
        self.comboBox_kasamifamily.addItem("")
        self.comboBox_kasamifamily.addItem("")
        self.comboBox_kasamifamily.addItem("")
        self.comboBox_kasamifamily.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_kasamifamily)
        self.pushButton_kasamifamily_clone = QtWidgets.QPushButton(self.kasamifamily)
        self.pushButton_kasamifamily_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_kasamifamily_clone.setObjectName("pushButton_kasamifamily_clone")
        self.horizontalLayout_8.addWidget(self.pushButton_kasamifamily_clone)
        self.gridLayout_31.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.graphicsView_kasamifamily = QtWidgets.QGraphicsView(self.kasamifamily)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_kasamifamily.sizePolicy().hasHeightForWidth())
        self.graphicsView_kasamifamily.setSizePolicy(sizePolicy)
        self.graphicsView_kasamifamily.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_kasamifamily.setObjectName("graphicsView_kasamifamily")
        self.gridLayout_31.addWidget(self.graphicsView_kasamifamily, 2, 0, 1, 2)
        self.listWidget_kasamifamily = QtWidgets.QListWidget(self.kasamifamily)
        self.listWidget_kasamifamily.setObjectName("listWidget_kasamifamily")
        self.gridLayout_31.addWidget(self.listWidget_kasamifamily, 0, 1, 1, 1)
        self.tabs.addTab(self.kasamifamily, "")
        self.ovsfsequence = QtWidgets.QWidget()
        self.ovsfsequence.setObjectName("ovsfsequence")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.ovsfsequence)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.groupBox_9 = QtWidgets.QGroupBox(self.ovsfsequence)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_32.setObjectName("gridLayout_32")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem19, 2, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem20, 1, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem21, 0, 0, 1, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_24.setObjectName("groupBox_24")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_24)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_25 = QtWidgets.QLabel(self.groupBox_24)
        self.label_25.setObjectName("label_25")
        self.gridLayout_33.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_ovsfsequence_sequence_length = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_ovsfsequence_sequence_length.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ovsfsequence_sequence_length.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_ovsfsequence_sequence_length.setObjectName("lineEdit_ovsfsequence_sequence_length")
        self.gridLayout_33.addWidget(self.lineEdit_ovsfsequence_sequence_length, 0, 1, 1, 1)
        self.gridLayout_32.addWidget(self.groupBox_24, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem22, 1, 1, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.pushButton_ovsfsequence_generatesequence = QtWidgets.QPushButton(self.ovsfsequence)
        self.pushButton_ovsfsequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ovsfsequence_generatesequence.setObjectName("pushButton_ovsfsequence_generatesequence")
        self.gridLayout_36.addWidget(self.pushButton_ovsfsequence_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_ovsfsequence_afkanalyse = QtWidgets.QPushButton(self.ovsfsequence)
        self.pushButton_ovsfsequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ovsfsequence_afkanalyse.setObjectName("pushButton_ovsfsequence_afkanalyse")
        self.horizontalLayout_9.addWidget(self.pushButton_ovsfsequence_afkanalyse)
        self.pushButton_ovsfsequence_kkfanalyse = QtWidgets.QPushButton(self.ovsfsequence)
        self.pushButton_ovsfsequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ovsfsequence_kkfanalyse.setObjectName("pushButton_ovsfsequence_kkfanalyse")
        self.horizontalLayout_9.addWidget(self.pushButton_ovsfsequence_kkfanalyse)
        self.pushButton_ovsfsequence_deleteall = QtWidgets.QPushButton(self.ovsfsequence)
        self.pushButton_ovsfsequence_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ovsfsequence_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_ovsfsequence_deleteall.setObjectName("pushButton_ovsfsequence_deleteall")
        self.horizontalLayout_9.addWidget(self.pushButton_ovsfsequence_deleteall)
        self.comboBox_ovsfsequence = QtWidgets.QComboBox(self.ovsfsequence)
        self.comboBox_ovsfsequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_ovsfsequence.setObjectName("comboBox_ovsfsequence")
        self.comboBox_ovsfsequence.addItem("")
        self.comboBox_ovsfsequence.addItem("")
        self.comboBox_ovsfsequence.addItem("")
        self.comboBox_ovsfsequence.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_ovsfsequence)
        self.pushButton_ovsfsequence_clone = QtWidgets.QPushButton(self.ovsfsequence)
        self.pushButton_ovsfsequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ovsfsequence_clone.setObjectName("pushButton_ovsfsequence_clone")
        self.horizontalLayout_9.addWidget(self.pushButton_ovsfsequence_clone)
        self.gridLayout_36.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.graphicsView_ovsfsequence = QtWidgets.QGraphicsView(self.ovsfsequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_ovsfsequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_ovsfsequence.setSizePolicy(sizePolicy)
        self.graphicsView_ovsfsequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_ovsfsequence.setObjectName("graphicsView_ovsfsequence")
        self.gridLayout_36.addWidget(self.graphicsView_ovsfsequence, 2, 0, 1, 2)
        self.listWidget_ovsfsequence = QtWidgets.QListWidget(self.ovsfsequence)
        self.listWidget_ovsfsequence.setObjectName("listWidget_ovsfsequence")
        self.gridLayout_36.addWidget(self.listWidget_ovsfsequence, 0, 1, 1, 1)
        self.tabs.addTab(self.ovsfsequence, "")
        self.golaysequence = QtWidgets.QWidget()
        self.golaysequence.setObjectName("golaysequence")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.golaysequence)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.groupBox_10 = QtWidgets.QGroupBox(self.golaysequence)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_34.setObjectName("gridLayout_34")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem23, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem24, 0, 1, 1, 1)
        self.gridLayout_39.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.pushButton_golaysequence_generatesequence = QtWidgets.QPushButton(self.golaysequence)
        self.pushButton_golaysequence_generatesequence.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_golaysequence_generatesequence.setObjectName("pushButton_golaysequence_generatesequence")
        self.gridLayout_39.addWidget(self.pushButton_golaysequence_generatesequence, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_golaysequence_afkanalyse = QtWidgets.QPushButton(self.golaysequence)
        self.pushButton_golaysequence_afkanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_golaysequence_afkanalyse.setObjectName("pushButton_golaysequence_afkanalyse")
        self.horizontalLayout_10.addWidget(self.pushButton_golaysequence_afkanalyse)
        self.pushButton_golaysequence_kkfanalyse = QtWidgets.QPushButton(self.golaysequence)
        self.pushButton_golaysequence_kkfanalyse.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_golaysequence_kkfanalyse.setObjectName("pushButton_golaysequence_kkfanalyse")
        self.horizontalLayout_10.addWidget(self.pushButton_golaysequence_kkfanalyse)
        self.pushButton_golaysequence_deleteall = QtWidgets.QPushButton(self.golaysequence)
        self.pushButton_golaysequence_deleteall.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_golaysequence_deleteall.setStyleSheet("background-color: rgb(255, 45, 45);\n"
"color: rgb(255, 255, 255)")
        self.pushButton_golaysequence_deleteall.setObjectName("pushButton_golaysequence_deleteall")
        self.horizontalLayout_10.addWidget(self.pushButton_golaysequence_deleteall)
        self.comboBox_golaysequence = QtWidgets.QComboBox(self.golaysequence)
        self.comboBox_golaysequence.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_golaysequence.setObjectName("comboBox_golaysequence")
        self.comboBox_golaysequence.addItem("")
        self.comboBox_golaysequence.addItem("")
        self.comboBox_golaysequence.addItem("")
        self.comboBox_golaysequence.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_golaysequence)
        self.pushButton_golaysequence_clone = QtWidgets.QPushButton(self.golaysequence)
        self.pushButton_golaysequence_clone.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_golaysequence_clone.setObjectName("pushButton_golaysequence_clone")
        self.horizontalLayout_10.addWidget(self.pushButton_golaysequence_clone)
        self.gridLayout_39.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.graphicsView_golaysequence = QtWidgets.QGraphicsView(self.golaysequence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_golaysequence.sizePolicy().hasHeightForWidth())
        self.graphicsView_golaysequence.setSizePolicy(sizePolicy)
        self.graphicsView_golaysequence.setMinimumSize(QtCore.QSize(0, 220))
        self.graphicsView_golaysequence.setObjectName("graphicsView_golaysequence")
        self.gridLayout_39.addWidget(self.graphicsView_golaysequence, 2, 0, 1, 2)
        self.listWidget_golaysequence = QtWidgets.QListWidget(self.golaysequence)
        self.listWidget_golaysequence.setObjectName("listWidget_golaysequence")
        self.gridLayout_39.addWidget(self.listWidget_golaysequence, 0, 1, 1, 1)
        self.tabs.addTab(self.golaysequence, "")
        self.gridLayout_37.addWidget(self.tabs, 0, 0, 1, 1)

        self.retranslateUi(Dialog_CodeGenerator)
        self.tabs.setCurrentIndex(0)
        self.tabs.currentChanged['int'].connect(Dialog_CodeGenerator.tabs)
        self.lineEdit_msequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditMSequencePropertiesRegister1Exponents)
        self.lineEdit_msequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditMSequencePropertiesRegister1InitialLoad)
        self.listWidget_msequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMSequence)
        self.pushButton_msequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonMSequenceGenerateSequence)
        self.pushButton_msequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonMSequenceAFKAnalyse)
        self.pushButton_msequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonMSequenceKKFAnalyse)
        self.pushButton_msequence_deletall.pressed.connect(Dialog_CodeGenerator.pushButtonMSequenceDeleteAll)
        self.pushButton_msequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonMSequenceClone)
        self.comboBox_msequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxMSequence)
        self.lineEdit_mfamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesRegister1Exponents)
        self.lineEdit_mfamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_mfamily_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesSequenceLength)
        self.lineEdit_mfamily_sequence_distance.editingFinished.connect(Dialog_CodeGenerator.lineEditMFamilyPropertiesSequenceDistance)
        self.pushButton_mfamily_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyGenerateSequence)
        self.pushButton_mfamily_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyAFKAnalyse)
        self.pushButton_mfamily_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyAFKAnalyse)
        self.pushButton_mfamily_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyKKFAnalyse)
        self.pushButton_mfamily_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyDeleteAll)
        self.comboBox_mfamily.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxMFamily)
        self.pushButton_mfamily_clone.pressed.connect(Dialog_CodeGenerator.pushButtonMFamilyClone)
        self.listWidget_mfamily_1.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMFamily1)
        self.listWidget_mfamily_2.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetMFamily2)
        self.lineEdit_goldsequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister1Exponents)
        self.lineEdit_goldsequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister1InitialLoad)
        self.lineEdit_goldsequence_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister2Exponents)
        self.lineEdit_goldsequence_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesRegister2InitialLoad)
        self.lineEdit_goldsequence_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesSequenceLength)
        self.lineEdit_goldsequence_sequence_distances.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldSequencePropertiesSequenceDistance)
        self.listWidget_goldsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGoldSequence)
        self.pushButton_goldsequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonGoldSequenceGenerateSequence)
        self.pushButton_goldsequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGoldSequenceAFKAnalyse)
        self.pushButton_goldsequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGoldSequenceKKFAnalyse)
        self.pushButton_goldsequence_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonGoldSequenceDeleteAll)
        self.comboBox_goldsequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxGoldSequence)
        self.pushButton_goldsequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonGoldSequenceClone)
        self.lineEdit_goldfamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister1Exponents)
        self.lineEdit_goldfamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_goldfamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditGoldFamilyPropertiesRegister2Exponents)
        self.listWidget_goldfamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGoldFamily)
        self.pushButton_goldfamily_clone.pressed.connect(Dialog_CodeGenerator.pushButtonGoldFamilyClone)
        self.comboBox_goldfamily.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxGoldFamily)
        self.pushButton_goldfamily_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonGoldFamilyDeleteAll)
        self.pushButton_goldfamily_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGoldFamilyKKFAnalyse)
        self.pushButton_goldfamily_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGoldFamilyAFKAnalyse)
        self.pushButton_goldfamily_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonGoldFamilyGenerateSequence)
        self.lineEdit_ogfsequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister1Exponents)
        self.lineEdit_ogfsequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister1InitialLoad)
        self.lineEdit_ogfsequence_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFSequencePropertiesRegister2Exponents)
        self.lineEdit_ogfsequence_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.pushButtonMFamilyClone)
        self.pushButton_ogfsequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonOGFSequenceGenerateSequence)
        self.pushButton_ogfsequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOGFSequenceAFKAnalyse)
        self.pushButton_ogfsequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOGFSequenceKKFAnalyse)
        self.pushButton_ogfsequence_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonOGFSequenceDeleteAll)
        self.comboBox_ogfsequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxOGFSequence)
        self.pushButton_ogfsequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonOGFSequenceClone)
        self.listWidget_ogfsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOGFSequence)
        self.lineEdit_ogffamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister1Exponents)
        self.lineEdit_ogffamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_ogffamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditOGFFamilyPropertiesRegister2Exponents)
        self.listWidget_goldfamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOGFFamily)
        self.pushButton_ogffamily_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonOGFFamilyGenerateSequence)
        self.pushButton_ogffamily_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOGFFamilyAFKAnalyse)
        self.pushButton_ogffamily_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOGFFamilyKKFAnalyse)
        self.pushButton_ogffamily_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonOGFFamilyDeleteAll)
        self.comboBox_ogffamily.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxOGFFamily)
        self.pushButton_ogffamily_clone.pressed.connect(Dialog_CodeGenerator.pushButtonOGFFamilyClone)
        self.lineEdit_kasamisequence_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiSequencePropertiesRegister1Exponents)
        self.lineEdit_kasamisequence_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiSequencePropertiesRegister1InitialLoad)
        self.listWidget_kasamisequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetKasamiSequence)
        self.pushButton_kasamisequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiSequenceGenerateSequence)
        self.pushButton_kasamisequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiSequenceAFKAnalyse)
        self.pushButton_kasamisequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiSequenceKKFAnalyse)
        self.pushButton_kasamisequence_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiSequenceDeleteAll)
        self.comboBox_kasamisequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxKasamiSequence)
        self.pushButton_kasamisequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiSequenceClone)
        self.lineEdit_kasamifamily_register1_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister1Exponents)
        self.lineEdit_kasamifamily_register1_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister1InitialLoad)
        self.lineEdit_kasamifamily_register2_exponents.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister2Exponents)
        self.lineEdit_kasamifamily_register2_initialload.editingFinished.connect(Dialog_CodeGenerator.lineEditKasamiFamilyPropertiesRegister2InitialLoad)
        self.listWidget_kasamifamily.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetKasamiFamily)
        self.pushButton_kasamifamily_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiFamilyGenerateSequence)
        self.pushButton_kasamifamily_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiFamilyAFKAnalyse)
        self.pushButton_kasamifamily_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiFamilyKKFAnalyse)
        self.pushButton_kasamifamily_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiFamilyDeleteAll)
        self.comboBox_kasamifamily.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxKasamiFamily)
        self.pushButton_kasamifamily_clone.pressed.connect(Dialog_CodeGenerator.pushButtonKasamiFamilyClone)
        self.lineEdit_ovsfsequence_sequence_length.editingFinished.connect(Dialog_CodeGenerator.lineEditOVSFSequenceSequenceLength)
        self.listWidget_ovsfsequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetOVSFSequence)
        self.pushButton_ovsfsequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonOVSFSequenceGenerateSequence)
        self.pushButton_ovsfsequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOVSFSequenceAFKAnalyse)
        self.pushButton_ovsfsequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonOVSFSequenceKKFAnalyse)
        self.pushButton_ovsfsequence_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonOVSFSequenceDeleteAll)
        self.comboBox_ovsfsequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxOVSFSequence)
        self.pushButton_ovsfsequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonOVSFSequenceClone)
        self.pushButton_golaysequence_generatesequence.pressed.connect(Dialog_CodeGenerator.pushButtonGolaySequenceGenerateSequence)
        self.listWidget_golaysequence.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(Dialog_CodeGenerator.listWidgetGolaySequence)
        self.pushButton_golaysequence_afkanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGolaySequenceAFKAnalyse)
        self.pushButton_golaysequence_kkfanalyse.pressed.connect(Dialog_CodeGenerator.pushButtonGolaySequenceKKFAnalyse)
        self.pushButton_golaysequence_deleteall.pressed.connect(Dialog_CodeGenerator.pushButtonGolaySequenceDeleteAll)
        self.comboBox_golaysequence.currentIndexChanged['int'].connect(Dialog_CodeGenerator.comboBoxGolaySequence)
        self.pushButton_golaysequence_clone.pressed.connect(Dialog_CodeGenerator.pushButtonGolaySequenceClone)
        QtCore.QMetaObject.connectSlotsByName(Dialog_CodeGenerator)

    def retranslateUi(self, Dialog_CodeGenerator):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CodeGenerator.setWindowTitle(_translate("Dialog_CodeGenerator", "RoCoS 2 - Code Generator"))
        self.pushButton_msequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_msequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_msequence_deletall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_msequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_msequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_msequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_msequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_msequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.groupBox.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_11.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_2.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.pushButton_msequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.tabs.setTabText(self.tabs.indexOf(self.msequence), _translate("Dialog_CodeGenerator", "m-Sequence"))
        self.pushButton_mfamily_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_mfamily_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_mfamily_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_mfamily.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_mfamily.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_mfamily.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_mfamily.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.comboBox_mfamily.setItemText(4, _translate("Dialog_CodeGenerator", "Channel MU"))
        self.pushButton_mfamily_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.pushButton_mfamily_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.groupBox_2.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_13.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_5.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.label_6.setText(_translate("Dialog_CodeGenerator", "Distances"))
        self.groupBox_12.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_3.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_4.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.mfamily), _translate("Dialog_CodeGenerator", "m-Family"))
        self.groupBox_3.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_23.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_23.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.label_24.setText(_translate("Dialog_CodeGenerator", "Distances"))
        self.groupBox_14.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_7.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_8.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_25.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_26.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_27.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.pushButton_goldsequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_goldsequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_goldsequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_goldsequence_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_goldsequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_goldsequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_goldsequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_goldsequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_goldsequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.goldsequence), _translate("Dialog_CodeGenerator", "Gold-Sequence"))
        self.groupBox_4.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_15.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_9.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_10.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_27.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_30.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.pushButton_goldfamily_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_goldfamily_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_goldfamily_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_goldfamily_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_goldfamily.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_goldfamily.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_goldfamily.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_goldfamily.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_goldfamily_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.goldfamily), _translate("Dialog_CodeGenerator", "Gold-Family"))
        self.groupBox_5.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_16.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_11.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_12.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_28.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_31.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_13.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.pushButton_ogfsequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_ogfsequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_ogfsequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_ogfsequence_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_ogfsequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_ogfsequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_ogfsequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_ogfsequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_ogfsequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.ogfsequence), _translate("Dialog_CodeGenerator", "OGF-Sequence"))
        self.groupBox_6.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_17.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_14.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_15.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_29.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_32.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.pushButton_ogffamily_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_ogffamily_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_ogffamily_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_ogffamily_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_ogffamily.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_ogffamily.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_ogffamily.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_ogffamily.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_ogffamily_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.ogffamily), _translate("Dialog_CodeGenerator", "OGF-Family"))
        self.groupBox_7.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_18.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_16.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_17.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.pushButton_kasamisequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_kasamisequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_kasamisequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_kasamisequence_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_kasamisequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_kasamisequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_kasamisequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_kasamisequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_kasamisequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.kasamisequence), _translate("Dialog_CodeGenerator", "Kasami-Sequence"))
        self.groupBox_8.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_19.setTitle(_translate("Dialog_CodeGenerator", "Register 1"))
        self.label_18.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_19.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.groupBox_20.setTitle(_translate("Dialog_CodeGenerator", "Register 2"))
        self.label_20.setText(_translate("Dialog_CodeGenerator", "Exponents"))
        self.label_21.setText(_translate("Dialog_CodeGenerator", "Initial Load"))
        self.pushButton_kasamifamily_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_kasamifamily_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_kasamifamily_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_kasamifamily_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_kasamifamily.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_kasamifamily.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_kasamifamily.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_kasamifamily.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_kasamifamily_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.kasamifamily), _translate("Dialog_CodeGenerator", "Kasami-Family"))
        self.groupBox_9.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.groupBox_24.setTitle(_translate("Dialog_CodeGenerator", "Sequence"))
        self.label_25.setText(_translate("Dialog_CodeGenerator", "Length"))
        self.pushButton_ovsfsequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_ovsfsequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_ovsfsequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_ovsfsequence_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_ovsfsequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_ovsfsequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_ovsfsequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_ovsfsequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_ovsfsequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.ovsfsequence), _translate("Dialog_CodeGenerator", "OVSF-Sequence"))
        self.groupBox_10.setTitle(_translate("Dialog_CodeGenerator", "Properties"))
        self.pushButton_golaysequence_generatesequence.setText(_translate("Dialog_CodeGenerator", "Generate Sequence"))
        self.pushButton_golaysequence_afkanalyse.setText(_translate("Dialog_CodeGenerator", "AFK Analyse"))
        self.pushButton_golaysequence_kkfanalyse.setText(_translate("Dialog_CodeGenerator", "KKF Analyse"))
        self.pushButton_golaysequence_deleteall.setText(_translate("Dialog_CodeGenerator", "Delete All"))
        self.comboBox_golaysequence.setItemText(0, _translate("Dialog_CodeGenerator", "Tx Sequence 1"))
        self.comboBox_golaysequence.setItemText(1, _translate("Dialog_CodeGenerator", "Tx Sequence 2"))
        self.comboBox_golaysequence.setItemText(2, _translate("Dialog_CodeGenerator", "Rx Sequence 1"))
        self.comboBox_golaysequence.setItemText(3, _translate("Dialog_CodeGenerator", "Rx Sequence 2"))
        self.pushButton_golaysequence_clone.setText(_translate("Dialog_CodeGenerator", "Clone"))
        self.tabs.setTabText(self.tabs.indexOf(self.golaysequence), _translate("Dialog_CodeGenerator", "Golay-Sequence"))
