# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tmarangoni/documents/RoCoS_2/src/ui/SimulationControl.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_SimulationControl(object):
    def setupUi(self, Dialog_SimulationControl):
        Dialog_SimulationControl.setObjectName("Dialog_SimulationControl")
        Dialog_SimulationControl.resize(377, 731)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_SimulationControl)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_simulation = QtWidgets.QComboBox(Dialog_SimulationControl)
        self.comboBox_simulation.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox_simulation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_simulation.setObjectName("comboBox_simulation")
        self.comboBox_simulation.addItem("")
        self.comboBox_simulation.addItem("")
        self.gridLayout.addWidget(self.comboBox_simulation, 2, 0, 1, 1)
        self.pushButton_abortsimulation = QtWidgets.QPushButton(Dialog_SimulationControl)
        self.pushButton_abortsimulation.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/simulation_abort.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_abortsimulation.setIcon(icon)
        self.pushButton_abortsimulation.setObjectName("pushButton_abortsimulation")
        self.gridLayout.addWidget(self.pushButton_abortsimulation, 4, 0, 1, 1)
        self.pushButton_startsimulation = QtWidgets.QPushButton(Dialog_SimulationControl)
        self.pushButton_startsimulation.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/simulation_start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_startsimulation.setIcon(icon1)
        self.pushButton_startsimulation.setObjectName("pushButton_startsimulation")
        self.gridLayout.addWidget(self.pushButton_startsimulation, 3, 0, 1, 1)
        self.pushButton_savesettings = QtWidgets.QPushButton(Dialog_SimulationControl)
        self.pushButton_savesettings.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_savesettings.setObjectName("pushButton_savesettings")
        self.gridLayout.addWidget(self.pushButton_savesettings, 3, 1, 1, 1)
        self.pushButton_saveresults = QtWidgets.QPushButton(Dialog_SimulationControl)
        self.pushButton_saveresults.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_saveresults.setObjectName("pushButton_saveresults")
        self.gridLayout.addWidget(self.pushButton_saveresults, 4, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog_SimulationControl)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_signals_simulation_bitsframes = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_signals_simulation_bitsframes.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_signals_simulation_bitsframes.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_signals_simulation_bitsframes.setObjectName("lineEdit_signals_simulation_bitsframes")
        self.gridLayout_6.addWidget(self.lineEdit_signals_simulation_bitsframes, 0, 1, 1, 1)
        self.lineEdit_signals_simulation_samplerate = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_signals_simulation_samplerate.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_signals_simulation_samplerate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_signals_simulation_samplerate.setObjectName("lineEdit_signals_simulation_samplerate")
        self.gridLayout_6.addWidget(self.lineEdit_signals_simulation_samplerate, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_signals_simulation_numberofsamples = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_signals_simulation_numberofsamples.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_signals_simulation_numberofsamples.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_signals_simulation_numberofsamples.setObjectName("lineEdit_signals_simulation_numberofsamples")
        self.gridLayout_6.addWidget(self.lineEdit_signals_simulation_numberofsamples, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_signals_show_histogramms = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_signals_show_histogramms.setObjectName("checkBox_signals_show_histogramms")
        self.gridLayout_5.addWidget(self.checkBox_signals_show_histogramms, 0, 0, 1, 1)
        self.checkBox_signals_show_running_window = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_signals_show_running_window.setObjectName("checkBox_signals_show_running_window")
        self.gridLayout_5.addWidget(self.checkBox_signals_show_running_window, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_signals_output_modulator = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_signals_output_modulator.setObjectName("checkBox_signals_output_modulator")
        self.gridLayout_3.addWidget(self.checkBox_signals_output_modulator, 2, 0, 1, 1)
        self.checkBox_signals_output_data = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_signals_output_data.setObjectName("checkBox_signals_output_data")
        self.gridLayout_3.addWidget(self.checkBox_signals_output_data, 0, 0, 1, 1)
        self.checkBox_signals_output_transmitter = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_signals_output_transmitter.setObjectName("checkBox_signals_output_transmitter")
        self.gridLayout_3.addWidget(self.checkBox_signals_output_transmitter, 1, 0, 1, 1)
        self.checkBox_signals_output_channel = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_signals_output_channel.setObjectName("checkBox_signals_output_channel")
        self.gridLayout_3.addWidget(self.checkBox_signals_output_channel, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_signals_data_generated = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_signals_data_generated.setObjectName("checkBox_signals_data_generated")
        self.gridLayout_4.addWidget(self.checkBox_signals_data_generated, 0, 0, 1, 1)
        self.checkBox_signals_data_estimated = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_signals_data_estimated.setObjectName("checkBox_signals_data_estimated")
        self.gridLayout_4.addWidget(self.checkBox_signals_data_estimated, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 3, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_histogramms_properties_signalbeforedecision = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_histogramms_properties_signalbeforedecision.setObjectName("checkBox_histogramms_properties_signalbeforedecision")
        self.gridLayout_8.addWidget(self.checkBox_histogramms_properties_signalbeforedecision, 1, 0, 1, 1)
        self.checkBox_histogramms_properties_sampledsignal = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_histogramms_properties_sampledsignal.setObjectName("checkBox_histogramms_properties_sampledsignal")
        self.gridLayout_8.addWidget(self.checkBox_histogramms_properties_sampledsignal, 2, 0, 1, 1)
        self.checkBox_histogramms_properties_dataoutput = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_histogramms_properties_dataoutput.setObjectName("checkBox_histogramms_properties_dataoutput")
        self.gridLayout_8.addWidget(self.checkBox_histogramms_properties_dataoutput, 0, 0, 1, 1)
        self.checkBox_histogramms_properties_errordistribution = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_histogramms_properties_errordistribution.setObjectName("checkBox_histogramms_properties_errordistribution")
        self.gridLayout_8.addWidget(self.checkBox_histogramms_properties_errordistribution, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_histogramms_simulation_granularity = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_histogramms_simulation_granularity.setEnabled(False)
        self.lineEdit_histogramms_simulation_granularity.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_histogramms_simulation_granularity.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_histogramms_simulation_granularity.setObjectName("lineEdit_histogramms_simulation_granularity")
        self.gridLayout_9.addWidget(self.lineEdit_histogramms_simulation_granularity, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 1, 2, 1, 1)
        self.checkBox_histogramms_simulation_automaticrangeestimation = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_histogramms_simulation_automaticrangeestimation.setObjectName("checkBox_histogramms_simulation_automaticrangeestimation")
        self.gridLayout_9.addWidget(self.checkBox_histogramms_simulation_automaticrangeestimation, 0, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox_6, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_BEP_MU_numberofusers = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_BEP_MU_numberofusers.setEnabled(False)
        self.lineEdit_BEP_MU_numberofusers.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_BEP_MU_numberofusers.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_MU_numberofusers.setObjectName("lineEdit_BEP_MU_numberofusers")
        self.gridLayout_12.addWidget(self.lineEdit_BEP_MU_numberofusers, 1, 1, 1, 1)
        self.checkBox_BEP_MU_activate = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_BEP_MU_activate.setObjectName("checkBox_BEP_MU_activate")
        self.gridLayout_12.addWidget(self.checkBox_BEP_MU_activate, 0, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_8, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 1, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 2, 2, 1, 1)
        self.lineEdit_BEP_simulation_timesamples = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_BEP_simulation_timesamples.setEnabled(False)
        self.lineEdit_BEP_simulation_timesamples.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_BEP_simulation_timesamples.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_simulation_timesamples.setObjectName("lineEdit_BEP_simulation_timesamples")
        self.gridLayout_13.addWidget(self.lineEdit_BEP_simulation_timesamples, 2, 1, 1, 1)
        self.checkBox_BEP_simulation_showfirsttimesamples = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_BEP_simulation_showfirsttimesamples.setObjectName("checkBox_BEP_simulation_showfirsttimesamples")
        self.gridLayout_13.addWidget(self.checkBox_BEP_simulation_showfirsttimesamples, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lineEdit_BEP_simulation_bitstosimulate = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_BEP_simulation_bitstosimulate.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_BEP_simulation_bitstosimulate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_simulation_bitstosimulate.setObjectName("lineEdit_BEP_simulation_bitstosimulate")
        self.horizontalLayout.addWidget(self.lineEdit_BEP_simulation_bitstosimulate)
        self.gridLayout_13.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.checkBox_BEP_simulation_showhistogramms = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_BEP_simulation_showhistogramms.setObjectName("checkBox_BEP_simulation_showhistogramms")
        self.gridLayout_13.addWidget(self.checkBox_BEP_simulation_showhistogramms, 3, 0, 1, 3)
        self.gridLayout_10.addWidget(self.groupBox_9, 2, 0, 1, 2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_BEP_SNR_range_start = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_BEP_SNR_range_start.setEnabled(False)
        self.lineEdit_BEP_SNR_range_start.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_BEP_SNR_range_start.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_SNR_range_start.setObjectName("lineEdit_BEP_SNR_range_start")
        self.gridLayout_11.addWidget(self.lineEdit_BEP_SNR_range_start, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_BEP_SNR_granularity = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_BEP_SNR_granularity.setEnabled(False)
        self.lineEdit_BEP_SNR_granularity.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_BEP_SNR_granularity.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_SNR_granularity.setObjectName("lineEdit_BEP_SNR_granularity")
        self.gridLayout_11.addWidget(self.lineEdit_BEP_SNR_granularity, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 2, 2, 1, 1)
        self.lineEdit_BEP_SNR_range_end = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_BEP_SNR_range_end.setEnabled(False)
        self.lineEdit_BEP_SNR_range_end.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_BEP_SNR_range_end.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_BEP_SNR_range_end.setObjectName("lineEdit_BEP_SNR_range_end")
        self.gridLayout_11.addWidget(self.lineEdit_BEP_SNR_range_end, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 2, 5, 1, 1)
        self.checkBox_BEP_SNR_activate = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_BEP_SNR_activate.setObjectName("checkBox_BEP_SNR_activate")
        self.gridLayout_11.addWidget(self.checkBox_BEP_SNR_activate, 0, 0, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 3, 2, 1, 4)
        self.gridLayout_10.addWidget(self.groupBox_7, 0, 0, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem10, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem11 = QtWidgets.QSpacerItem(20, 378, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem11, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.checkBox_showsimulationprogress = QtWidgets.QCheckBox(Dialog_SimulationControl)
        self.checkBox_showsimulationprogress.setObjectName("checkBox_showsimulationprogress")
        self.gridLayout.addWidget(self.checkBox_showsimulationprogress, 1, 0, 1, 2)

        self.retranslateUi(Dialog_SimulationControl)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_saveresults.pressed.connect(Dialog_SimulationControl.pushButtonSaveResults)
        self.pushButton_savesettings.pressed.connect(Dialog_SimulationControl.pushButtonSaveSettings)
        self.pushButton_startsimulation.pressed.connect(Dialog_SimulationControl.pushButtonStartSimulation)
        self.pushButton_abortsimulation.pressed.connect(Dialog_SimulationControl.pushButtonAbortSimulation)
        self.comboBox_simulation.activated['int'].connect(Dialog_SimulationControl.comboBoxSimulation)
        self.checkBox_showsimulationprogress.toggled['bool'].connect(Dialog_SimulationControl.checkBoxShowSimulationProgress)
        self.tabWidget.currentChanged['int'].connect(Dialog_SimulationControl.tabWidget)
        self.checkBox_signals_output_data.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsOutputData)
        self.checkBox_signals_output_transmitter.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsOutputTransmitter)
        self.groupBox.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsOutputModulator)
        self.checkBox_signals_output_channel.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsOutputChannel)
        self.checkBox_signals_data_generated.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsDataGenerated)
        self.checkBox_signals_data_estimated.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsDataEstimated)
        self.checkBox_signals_show_histogramms.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsShowHistogramms)
        self.checkBox_signals_show_running_window.toggled['bool'].connect(Dialog_SimulationControl.checkBoxSignalsShowRunningWindow)
        self.lineEdit_signals_simulation_bitsframes.editingFinished.connect(Dialog_SimulationControl.lineEditSignalsSimulationBitsFrame)
        self.lineEdit_signals_simulation_samplerate.editingFinished.connect(Dialog_SimulationControl.lineEditSignalsSimulationSamplerate)
        self.lineEdit_signals_simulation_numberofsamples.editingFinished.connect(Dialog_SimulationControl.lineEditSignalsSimulationNumberOfShownSamples)
        self.checkBox_histogramms_properties_dataoutput.toggled['bool'].connect(Dialog_SimulationControl.checkBoxHistogrammsPropertiesDataOutput)
        self.checkBox_histogramms_properties_signalbeforedecision.toggled['bool'].connect(Dialog_SimulationControl.checkBoxHistogrammsPropertiesSignalBeforeDecision)
        self.checkBox_histogramms_properties_sampledsignal.toggled['bool'].connect(Dialog_SimulationControl.checkBoxHistogrammsPropertiesSampledSignal)
        self.checkBox_histogramms_properties_errordistribution.toggled['bool'].connect(Dialog_SimulationControl.checkBoxHistogrammsPropertiesErrorDistribution)
        self.checkBox_histogramms_simulation_automaticrangeestimation.toggled['bool'].connect(Dialog_SimulationControl.checkBoxHistogrammsSimulationAutomaticRangeEstimation)
        self.lineEdit_histogramms_simulation_granularity.editingFinished.connect(Dialog_SimulationControl.lineEditHistogrammsSimulationGranularity)
        self.checkBox_BEP_SNR_activate.toggled['bool'].connect(Dialog_SimulationControl.checkBoxBEPSimulationBEPSNRActivate)
        self.checkBox_BEP_MU_activate.toggled['bool'].connect(Dialog_SimulationControl.checkBoxBEPSimulationBEPMUsActivate)
        self.checkBox_BEP_simulation_showfirsttimesamples.toggled['bool'].connect(Dialog_SimulationControl.checkBoxBEPSimulationSimulationShowFirst)
        self.checkBox_BEP_simulation_showhistogramms.toggled['bool'].connect(Dialog_SimulationControl.checkBoxBEPSimulationSimulationShowHistogramms)
        self.lineEdit_BEP_SNR_range_start.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationBEPSNRSNRRangeFrom)
        self.lineEdit_BEP_SNR_range_end.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationBEPSNRSNRRangeTo)
        self.lineEdit_BEP_SNR_granularity.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationBEPSNRGranularity)
        self.lineEdit_BEP_MU_numberofusers.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationBEPMUsNrOfUsers)
        self.lineEdit_BEP_simulation_bitstosimulate.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationBEPSNRNrOfBitsToSimulate)
        self.lineEdit_BEP_simulation_timesamples.editingFinished.connect(Dialog_SimulationControl.lineEditBEPSimulationSimulationTimeSamples)
        self.checkBox_histogramms_simulation_automaticrangeestimation.toggled['bool'].connect(self.lineEdit_histogramms_simulation_granularity.setEnabled)
        self.checkBox_BEP_SNR_activate.toggled['bool'].connect(self.lineEdit_BEP_SNR_range_start.setEnabled)
        self.checkBox_BEP_SNR_activate.toggled['bool'].connect(self.lineEdit_BEP_SNR_range_end.setEnabled)
        self.checkBox_BEP_SNR_activate.toggled['bool'].connect(self.lineEdit_BEP_SNR_granularity.setEnabled)
        self.checkBox_BEP_MU_activate.toggled['bool'].connect(self.lineEdit_BEP_MU_numberofusers.setEnabled)
        self.checkBox_BEP_simulation_showfirsttimesamples.toggled['bool'].connect(self.lineEdit_BEP_simulation_timesamples.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog_SimulationControl)

    def retranslateUi(self, Dialog_SimulationControl):
        _translate = QtCore.QCoreApplication.translate
        Dialog_SimulationControl.setWindowTitle(_translate("Dialog_SimulationControl", "RoCoS 2 - Simulation Control"))
        self.comboBox_simulation.setItemText(0, _translate("Dialog_SimulationControl", "Time Signal Simulation"))
        self.comboBox_simulation.setItemText(1, _translate("Dialog_SimulationControl", "BitErrorP Simulation"))
        self.pushButton_abortsimulation.setText(_translate("Dialog_SimulationControl", "Abort Simulation"))
        self.pushButton_startsimulation.setText(_translate("Dialog_SimulationControl", "Start Simulation"))
        self.pushButton_savesettings.setText(_translate("Dialog_SimulationControl", "Save Settings"))
        self.pushButton_saveresults.setText(_translate("Dialog_SimulationControl", "Save Results"))
        self.groupBox_4.setTitle(_translate("Dialog_SimulationControl", "Simulation"))
        self.label_2.setText(_translate("Dialog_SimulationControl", "Samplerate"))
        self.label.setText(_translate("Dialog_SimulationControl", "Bits/Frame"))
        self.label_3.setText(_translate("Dialog_SimulationControl", "Number of shown Samples"))
        self.groupBox_3.setTitle(_translate("Dialog_SimulationControl", "Show"))
        self.checkBox_signals_show_histogramms.setText(_translate("Dialog_SimulationControl", "Histogramms"))
        self.checkBox_signals_show_running_window.setText(_translate("Dialog_SimulationControl", "Running Window"))
        self.groupBox.setTitle(_translate("Dialog_SimulationControl", "Output"))
        self.checkBox_signals_output_modulator.setText(_translate("Dialog_SimulationControl", "Modulator"))
        self.checkBox_signals_output_data.setText(_translate("Dialog_SimulationControl", "Data"))
        self.checkBox_signals_output_transmitter.setText(_translate("Dialog_SimulationControl", "Transmitter"))
        self.checkBox_signals_output_channel.setText(_translate("Dialog_SimulationControl", "Channel"))
        self.groupBox_2.setTitle(_translate("Dialog_SimulationControl", "Data"))
        self.checkBox_signals_data_generated.setText(_translate("Dialog_SimulationControl", "Generated"))
        self.checkBox_signals_data_estimated.setText(_translate("Dialog_SimulationControl", "Estimated"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_SimulationControl", "Signals"))
        self.groupBox_5.setTitle(_translate("Dialog_SimulationControl", "Properties"))
        self.checkBox_histogramms_properties_signalbeforedecision.setText(_translate("Dialog_SimulationControl", "Signal before decision"))
        self.checkBox_histogramms_properties_sampledsignal.setText(_translate("Dialog_SimulationControl", "Sampled Signal"))
        self.checkBox_histogramms_properties_dataoutput.setText(_translate("Dialog_SimulationControl", "Data Output"))
        self.checkBox_histogramms_properties_errordistribution.setText(_translate("Dialog_SimulationControl", "Error Distribution"))
        self.groupBox_6.setTitle(_translate("Dialog_SimulationControl", "Simulation"))
        self.label_4.setText(_translate("Dialog_SimulationControl", "Granularity"))
        self.label_5.setText(_translate("Dialog_SimulationControl", "pts"))
        self.checkBox_histogramms_simulation_automaticrangeestimation.setText(_translate("Dialog_SimulationControl", "Automatic Range Estimation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_SimulationControl", "Histogramms"))
        self.groupBox_8.setTitle(_translate("Dialog_SimulationControl", "BEP/MUs"))
        self.label_12.setText(_translate("Dialog_SimulationControl", "Nr of Users"))
        self.checkBox_BEP_MU_activate.setText(_translate("Dialog_SimulationControl", "Activate"))
        self.groupBox_9.setTitle(_translate("Dialog_SimulationControl", "Simulation"))
        self.label_14.setText(_translate("Dialog_SimulationControl", "Time Samples"))
        self.checkBox_BEP_simulation_showfirsttimesamples.setText(_translate("Dialog_SimulationControl", "Show first"))
        self.label_13.setText(_translate("Dialog_SimulationControl", "Nr of Bits to simulate 10^"))
        self.checkBox_BEP_simulation_showhistogramms.setText(_translate("Dialog_SimulationControl", "Show Histogramms"))
        self.groupBox_7.setTitle(_translate("Dialog_SimulationControl", "BEP/SNR"))
        self.label_7.setText(_translate("Dialog_SimulationControl", "Granularity"))
        self.label_6.setText(_translate("Dialog_SimulationControl", "SNR Range from"))
        self.label_10.setText(_translate("Dialog_SimulationControl", "to"))
        self.label_8.setText(_translate("Dialog_SimulationControl", "dB"))
        self.label_11.setText(_translate("Dialog_SimulationControl", "dB"))
        self.checkBox_BEP_SNR_activate.setText(_translate("Dialog_SimulationControl", "Activate"))
        self.label_9.setText(_translate("Dialog_SimulationControl", "Pts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog_SimulationControl", "BEP Simulation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog_SimulationControl", "Synch Simulation"))
        self.checkBox_showsimulationprogress.setText(_translate("Dialog_SimulationControl", "Show Simulation Progress"))
import resources
